#!/usr/bin/env python
'''
generate a MAVLink test suite

Copyright Andrew Tridgell 2011
Released under GNU GPL version 3 or later
'''

import sys, textwrap
from optparse import OptionParser
import mavutil

def gen_value(f, i):
    '''generate a test value for the ith field of a message'''
    type = f.type

    # could be an array
    if type.find("[") != -1:
        # hack for now
        return '"%s%u"' % (f.name, i)

    if type == 'float':
        return 17.0 + i*7
    if type == 'char':
        return 'A' + i
    if type == 'int8_t':
        return 5 + i
    if type in ['int8_t', 'uint8_t']:
        return 5 + i
    if type in ['uint8_t_mavlink_version']:
        return 2
    if type in ['int16_t', 'uint16_t']:
        return 17235 + i*52
    if type in ['int32_t', 'uint32_t']:
        return 963497464 + i*52
    if type in ['int64_t', 'uint64_t']:
        return 9223372036854775807 + i*63


def generate_preamble(outf, msgs, args):
    outf.write("""
'''
MAVLink protocol test implementation (auto-generated by mavtestgen.py)

Generated from: %s

Note: this file has been auto-generated. DO NOT EDIT
'''

import mavlink

def generate_outputs(mav):
	'''generate all message types as outputs'''
""")

def generate_methods(outf, msgs):
    for m in msgs:
	outf.write("\tmav.%s_send(" % m.name.lower())
        for i in range(0, len(m.fields)):
            f = m.fields[i]
            outf.write("%s=%s" % (f.name, gen_value(f, i)))
            if i != len(m.fields)-1:
                outf.write(",")
        outf.write(")\n")

parser = OptionParser("mavtestgen.py [options] <XML files>")
parser.add_option("-o", "--output", dest="output", default="mavtest.py", help="output file")
(opts, args) = parser.parse_args()

if len(args) < 1:
    parser.error("You must supply at least one MAVLink XML protocol definition")
    

msgs = []
enums = []

for fname in args:
	(m, e) = mavutil.parse_mavlink_xml(fname)
        msgs.extend(m)
        enums.extend(e)


if mavutil.check_duplicates(msgs):
    sys.exit(1)

print("Found %u MAVLink message types" % len(msgs))
print("Generating %s" % opts.output)

outf = open(opts.output, "w")

generate_preamble(outf, msgs, args)
generate_methods(outf, msgs)
outf.close()
print("Generated %s OK" % opts.output)
